apiVersion: v2
name: dynamic-reverse-proxy
version: 0.2.1
description: Dynamic path-based reverse proxy for Kubernetes, packaged as a Helm chart
type: application
icon: https://raw.githubusercontent.com/gregbowyer84/dynamic-reverse-proxy-helm/main/assets/icon.svg