apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-proxy.fullname" . }}
  namespace: {{ include "nginx-proxy.namespace" . }}
  labels:
    {{- include "nginx-proxy.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "nginx-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
      name: http
    {{- if .Values.service.https.enabled }}
    - protocol: TCP
      port: {{ .Values.service.https.port }}
      targetPort: 443
      name: https
    {{- end }}
  type: {{ .Values.service.type }}
